version: '3'
services:
  db-passenger-service:
    image: postgres
    ports:
      - 5444:5432
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: passenger-db
