spring:
  application:
    name: payment-service
  profiles:
    include: secrets
  datasource:
    url: jdbc:postgresql://localhost:${driversDbHost}/payment-db
    driver-class-name:  org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  pattern:
    console: "%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n"