spring:
  application:
    name: payment-service

  datasource:
    url: ${paymentDbUrl}
    driver-class-name:  org.postgresql.Driver
    username: ${dbPassword}
    password: ${dbUsername}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

stripe:
  public: ${stripePublicKey}
  secret: ${stripeSecretKey}

logging:
  pattern:
    console: "%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n"