
server:
  port: 8083

spring:
  liquibase:
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5446/ride-db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none