
server:
  port: 8082

spring:
  application:
    name: driver-service
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
  datasource:
    url: jdbc:postgresql://localhost:${dbHost}/payment-db
    username: ${dbUsername}
    password: ${dbPassword}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  kafka:
    consumer:
      group-id:
        ride: ride-creation-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    bootstrap-servers: localhost:9092
topic:
  name:
    ride: create.ride
    driver: available.driver
kafka:
  bootstrap-servers: localhost:9092
  partitions:
    count: 1
  replicas:
    count: 1
feign:
  client:
    ride:
      name: ride
      path: /api/v1/rides

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  pattern:
    console: "%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  endpoint:
    prometheus:
      enabled: true

