
server:
  port: 8083

spring:
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
  datasource:
    url: jdbc:postgresql://localhost:5446/ride-db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

feign:
  client:
    passenger:
      url: http://localhost:8081
      name: passenger
      path: /api/v1/passengers
    driver:
      url: http://localhost:8082
      name: driver
      path: /api/v1/drivers
