
server:
  port: 8083

mail:
  test-mail: "alexey_tsurkan@mail.ru"

spring:
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-ride-master.xml
  datasource:
    url: jdbc:postgresql://localhost:5446/ride-db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  kafka:
    consumer:
      group-id:
        driver: driver-creation-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    bootstrap-servers: localhost:9092
  mail:
    password: eYhQkUaeGTtSajKuvhXS
    username: modsen-taxi123@mail.ru
topic:
  name:
    ride: create.ride
    driver: available.driver
kafka:
  bootstrap-servers: localhost:9092
  partitions:
    count: 1
  replicas:
    count: 1

feign:
  client:
    passenger:
      url: http://localhost:8081
      name: passenger
      path: /api/v1/passengers
    driver:
      url: http://localhost:8082
      name: driver
      path: /api/v1/drivers
    payment:
      url: http://localhost:8080
      name: payment
      path: /api/v1/payment

