
server:
  port: 8083

mail:
  test-mail: "alexey_tsurkan@mail.ru"

spring:
  application:
    name: ride-service
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-ride-master.xml
  datasource:
    url: jdbc:postgresql://localhost:${dbHost}/ride-db
    username: ${dbUsername}
    password: ${dbPassword}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  kafka:
    consumer:
      group-id:
        driver: driver-creation-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    bootstrap-servers: localhost:9092
  mail:
    password: eYhQkUaeGTtSajKuvhXS
    username: modsen-taxi123@mail.ru
topic:
  name:
    ride: create.ride
    driver: available.driver
kafka:
  bootstrap-servers: localhost:9092

  partitions:
    count: 1
  replicas:
    count: 1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  pattern:
    console: "%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n"


feign:
  client:
    passenger:
      name: passenger-service
      path: /api/v1/passengers
    driver:
      name: driver-service
      path: /api/v1/drivers
    payment:
      name: payment-service
      path: /api/v1/payment


management:
  endpoints:
    web:
      exposure:
        include: prometheus
  endpoint:
    prometheus:
      enabled: true
