server:
  port: 8081

spring:
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
  datasource:
    url: ${passengerDbUrl}
    username: ${dbPassword}
    password: ${dbUsername}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  application:
    name: passenger-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/cab-aggreagator-realm
          jwk-set-uri: http://localhost:8080/realms/cab-aggreagator-realm/protocol/openid-connect/certs


feign:
  client:
    ride:
      name: ride
      path: /api/v1/rides
jwt:
  auth:
    converter:
      resource-id: cab-aggregator-client
      principal-attribute: sub
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  pattern:
    console: "%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n"