server:
  port: 8081

spring:
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
  datasource:
    url: ${passengerDbUrl}
    username: ${dbPassword}
    password: ${dbUsername}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  application:
    name: passenger-service

feign:
  client:
    ride:
      url: ${rideServiceUrl}
      name: ride
      path: /api/v1/rides

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  pattern:
    console: "%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n"