spring:
  cloud:
    gateway:
      routes:
        - id: getAllPassengers
          uri: lb://passenger-service
          predicates:
            - Path=/api/v1/passengers
            - Method=GET

        - id: createPassenger
          uri: lb://passenger-service
          predicates:
            - Path=/api/v1/passengers
            - Method=POST

        - id: deletePassenger
          uri: lb://passenger-service
          predicates:
            - Path=/api/v1/passengers/{id}
            - Method=DELETE

        - id: getPassenger
          uri: lb://passenger-service
          predicates:
            - Path=/api/v1/passengers/{id}
            - Method=GET

        - id: updatePassenger
          uri: lb://passenger-service
          predicates:
            - Path=/api/v1/passengers/{id}
            - Method=PUT

        - id: getPagePassenger
          uri: lb://passenger-service
          predicates:
            - Path=/api/v1/passengers/page
            - Method=GET

        - id: addRatingPassenger
          uri: lb://passenger-service
          predicates:
            - Path=/api/v1/passengers/{passengerId}/rating
            - Method=PATCH
