spring:
  cloud:
    gateway:
      routes:
        - id: driverService
          uri: lb://driver-service
          predicates:
            - Path=/api/v1/drivers/**
          filters:
            - name: CircuitBreaker
              args:
                name: auto-service-circuit
                fallbackUri: forward://fallback/driver-service

        - id: autoService
          uri: lb://driver-service
          predicates:
            - Path=/api/v1/autos/**
          filters:
            - name: CircuitBreaker
              args:
                name: driver-service-circuit
                fallbackUri: forward://fallback/driver-service

        - id: passengerService
          uri: lb://passenger-service
          predicates:
            - Path=/api/v1/passengers/**
          filters:
            - name: CircuitBreaker
              args:
                name: passengers-service-circuit
                fallbackUri: forward://fallback/passenger-service

        - id: rideService
          uri: lb://ride-service
          predicates:
            - Path=/api/v1/rides/**
          filters:
            - name: CircuitBreaker
              args:
                name: ride-service-circuit
                fallbackUri: forward://fallback/ride-service

        - id: paymentService
          uri: lb://payment-service
          predicates:
            - Path=/api/v1/payment/**
          filters:
            - name: CircuitBreaker
              args:
                name: payment-service-circuit
                fallbackUri: forward://fallback/payment-service

